apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: application-pipeline-run-2
spec:
  pipelineRef:
    name: application-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: git
  params:
    - name: pathToContext
      value: "."
    - name: pathToDockerfile
      default: "Dockerfile"
    - name: pathToYamlFile
      value: "knative/knative-service.yaml"
    - name: imageUrl
      value: "docker.io/hfd2dsacx/micronaut"
    - name: imageTag
      value: "latest"
  serviceAccountName: build-bot
