apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image-from-source
spec:
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: .
    - name: pathToDockerfile
      description: The path to the dockerfile to build
      default: Dockerfile
    - name: imageUrl
      description: value should be like - us.icr.io/test_namespace/builtImageApp
    - name: imageTag
      description: Tag to apply to the built image
  resources:
    inputs:
      - name: git-source
        type: git

  steps:
    - name: list-src
      image: alpine
      command:
        - "ls"
      args:
        - "$(resources.inputs.git-source.path)"
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.3.0
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker      
      command:
        - /kaniko/executor
      args:
        - "--dockerfile=$(params.pathToDockerfile)"
        - "--destination=$(params.imageUrl):$(params.imageTag)"
        - "--context=$(resources.inputs.git-source.path)/$(params.pathToContext)/"
