apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-application
spec:
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: .
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: deploy.yaml
    - name: imageUrl
      description: Url of image repository
      default: url
    - name: imageTag
      description: Tag of the images to be used.
      default: "latest"
  resources:
    inputs:
      - name: git-source
        type: git
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;IMAGE;$(params.imageUrl):$(params.imageTag);g"
        - "$(resources.inputs.git-source.path)/$(params.pathToContext)/$(params.pathToYamlFile)"
    - name: deploy-app
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(resources.inputs.git-source.path)/$(params.pathToContext)/$(params.pathToYamlFile)"

